version: '3.1'

services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pythonDS
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/usr/src/app
    command: jupyter-lab --ip 0.0.0.0 --port 8888 --allow-root